### ISSUE TITLE
Error with CocoaPods when trying to deploy on iOS

### ISSUE THREAD

**Issue by joaowd** [pycampers/flutter-rx-ble#2] opened 2019-05-24 10:42 UTC
I get the following error when I try to deploy in iOS:

```
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      A plugin_scaffold
      A rx_ble
      R flutter_bluetooth_serial
      - Flutter
      - flutter_picker
      - fluttertoast
      - image_picker
      - orientation
      - path_provider
      - shared_preferences
      - url_launcher
    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `flutter_picker` from `.symlinks/plugins/flutter_picker/ios`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `orientation` from `.symlinks/plugins/orientation/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `plugin_scaffold` from `.symlinks/plugins/plugin_scaffold/ios`
    -> Fetching podspec for `rx_ble` from `.symlinks/plugins/rx_ble/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    Resolving dependencies of `Podfile`
    Comparing resolved specification to the sandbox manifest
      A RxAtomic
      A RxBluetoothKit
      A RxSwift
      A flutter_bluetooth_serial
      A plugin_scaffold
      A rx_ble
      - Flutter
      - flutter_picker
      - fluttertoast
      - image_picker
      - orientation
      - path_provider
      - shared_preferences
      - url_launcher
    Downloading dependencies
     -> Using Flutter (1.0.0)
    -> Installing RxAtomic (4.4.0)
      > Copying RxAtomic from `/Users/joaopalma/Library/Caches/CocoaPods/Pods/Release/RxAtomic/4.4.0-eacf6` to `Pods/RxAtomic`
    -> Installing RxBluetoothKit (5.1.4)
      > Copying RxBluetoothKit from `/Users/joaopalma/Library/Caches/CocoaPods/Pods/Release/RxBluetoothKit/5.1.4-d18f7` to `Pods/RxBluetoothKit`
    -> Installing RxSwift (4.4.0)
      > Copying RxSwift from `/Users/joaopalma/Library/Caches/CocoaPods/Pods/Release/RxSwift/4.4.0-5976e` to `Pods/RxSwift`
    -> Using flutter_picker (0.0.1)
    -> Using fluttertoast (0.0.2)
    -> Using image_picker (0.0.1)
    -> Using orientation (0.0.1)
    -> Using path_provider (0.0.1)
    -> Installing plugin_scaffold (0.0.1)
    -> Installing rx_ble (0.0.1)
    -> Using shared_preferences (0.0.1)
    -> Using url_launcher (0.0.1)
      - Running pre install hooks
    [!] The following Swift pods cannot yet be integrated as static libraries:
    The Swift pod `RxBluetoothKit` depends upon `RxAtomic`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
    The Swift pod `RxSwift` depends upon `RxAtomic`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
    The Swift pod `rx_ble` depends upon `RxAtomic`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:135:in `verify_swift_pods_have_module_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:415:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:118:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.5.3_1/libexec/bin/pod:22:in `<main>'
Error output from CocoaPods:
↳
        WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:
        export LANG=en_US.UTF-8
        
    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Error running pod install
```

**Comment by devxpy** [comment] 2019-05-24 12:16
Hey! 

This looks like a dependency resolver issue caused by another package in your application.

Could you please try the workaround suggested [here](https://github.com/ReactiveX/RxSwift/issues/1800)?

**Comment by joaowd** [comment] 2019-05-24 13:35
To add 'use_modular_headers!' to the Podfile inside of the ios folder?

**Comment by joaowd** [comment] 2019-05-24 14:42
After trying to add

- use_modular_headers
-  pod 'RxAtomic', '~> 4.0', :modular_headers => true

I get this error:

    ** BUILD FAILED **
Xcode's output:
↳
    /Users/joaopalma/Development/flutter/.pub-cache/hosted/pub.dartlang.org/plugin_scaffold-0.0.1/ios/Classes/PluginScaffoldPlugin.m:2:9: fatal error: 'plugin_scaffold/plugin_scaffold-Swift.h' file not found
    #import <plugin_scaffold/plugin_scaffold-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the precompiled application for the device.

**Comment by joaowd** [comment] 2019-05-24 16:00
If i try to use 'use_modeular_header!" 

I get this error:

Xcode's output:
↳
    /Users/joaopalma/Development/flutter/.pub-cache/hosted/pub.dartlang.org/plugin_scaffold-0.0.1/ios/Classes/PluginScaffoldPlugin.m:2:9: fatal error: 'plugin_scaffold/plugin_scaffold-Swift.h' file not found
    #import <plugin_scaffold/plugin_scaffold-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the precompiled application for the device.

**Comment by devxpy** [comment] 2019-05-25 12:12
Hmm, weird.

Does the example app work for you?

Also, does it fail even when you try to install the plugin in a fresh project?

**Comment by devxpy** [comment] 2019-05-25 16:59
If it works with a fresh project, could you please share the list of your dependencies? 

My guess would be that there's one dependency that's causing some sort of conflict.

**Comment by joaowd** [comment] 2019-05-28 09:07
Trying the example app:

- In android, I have the exact same error that is in the other issue that I created.
- In iOS, it works.

Dependencies:

  cupertino_icons: ^0.1.2
  rxdart: ^0.20.0
  rx_command: ^4.1.0
  rx_widgets: ^2.2.0
  get_it: ^1.0.2
  virgil: ^0.8.1
  flutter_svg: ^0.13.0+1
  url_launcher: ^5.0.1
  sembast: ^1.13.3+1
  path_provider: ^0.5.0+1
  meta: ^1.1.6
  image_picker: ^0.5.0+3
  shared_preferences: ^0.5.1+1
  auto_size_text: ^0.3.0
  flutter_picker: ^1.0.7
  tuple: ^1.0.2
  flutter_slidable: ^0.4.9
  intl: ^0.15.7
  fluttertoast: ^3.0.1
  overlay_support: ^0.0.4
  keyboard_actions: ^1.0.3
  groovin_material_icons: ^1.1.6
  transparent_image: ^0.1.0
  flutter_sticky_header: ^0.3.4
  uuid: ^2.0.0
  charts_flutter: ^0.6.0
  clippy_flutter: ^1.1.0
  orientation: ^1.0.4
  flarts: ^0.1.0
  rx_ble: ^0.5.3

**Comment by joaowd** [comment] 2019-05-28 10:17
Update:

I created a new flutter project and just added this dependency, and I still have the same error above, you probably have some problem on the plugin_scaffold project ?

**Comment by devxpy** [comment] 2019-05-28 12:26
That's weird. Can you post the output of `$ flutter doctor -v` here? I have 2 projects here that work fine.

**Comment by joaowd** [comment] 2019-05-28 13:15
[✓] Flutter (Channel dev, v1.6.3, on Mac OS X 10.14.5 18F132, locale en-PT)
    • Flutter version 1.6.3 at /Users/joaopalma/Development/flutter
    • Framework revision bc7bc94083 (5 days ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/joaopalma/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • iPhone Xʀ • 8AA77F64-292A-48C6-A72E-06A4D2DAE54A 
    • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

**Comment by devxpy** [comment] 2019-05-28 13:34
Hmm, Can we try to match-up our tooling versions, maybe that's causing it?

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en)
    • Flutter version 1.5.4-hotfix.2 at /Users/dev/Tools/flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5549111/Android Studio 3.5
      Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b02)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0.beta.3

[✓] Android Studio
    • Android Studio at /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5549111/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 35.3.2
    • Dart plugin version 191.7019
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b02)
```

**Comment by joaowd** [comment] 2019-05-28 14:46
Alright, I'm going to try it.

**Comment by joaowd** [comment] 2019-05-28 15:01
After updating the tooling versions I got this error:

[!] Unable to determine Swift version for the following pods:
    - `plugin_scaffold` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    - `rx_ble` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by joaowd** [comment] 2019-05-28 15:56
this helped me resolving the issue:

https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482

**Comment by devxpy** [comment] 2019-05-28 16:26
Awesome! Glad that you got it working.

I will see if I can set the `SWIFT_VERSION` anywhere. Maybe that will help future users.

Please close the issue if it has been resolved.

**Closed** 2019-05-29 09:03 UTC
